name: h3_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  oktoast: ^2.3.2
  flutter_easyloading: ^2.0.1
  permission_handler: ^5.0.1+1
  permission_handler_platform_interface: ^2.0.1
  flutter_keyboard_visibility: ^3.3.0
  flutter_spinkit: ^4.1.2+1
  http: ^0.12.2
  image: ^2.1.18
  community_material_icon: ^5.4.55
  sqflite: ^1.3.2+1  
  package_info: ^0.4.3+4
  crypto: ^2.1.5
  path_provider: ^1.6.28
  ansicolor: ^1.0.2 
  fluro: ^1.7.7
  bloc: ^6.1.0
  flutter_bloc: ^6.0.6
  equatable: ^1.2.5
  quiver: ^2.1.5
  flutter_custom_dialog: ^1.0.20
  device_info: ^1.0.0
  dio: ^3.0.10
  get_ip: ^0.4.0
  system_info: ^0.1.3
  sprintf: ^5.0.0
  connectivity: ^2.0.1
  dart_notification_center: ^1.0.0+1
  dart_extensions: ^1.0.2
  rational: ^0.3.8
  xml_parser: ^0.1.2
  encrypt: ^4.1.0
  string_unescape: ^1.5.1
  barcode_scan: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  assets:
    - assets/
    # - assets/js/
    - assets/fonts/
    - assets/images/
    - assets/images/download/
    - assets/images/login/
    # - assets/images/home/
    # - assets/template/
    # - assets/template/printer/

  fonts:
    - family: Alibaba PuHuiTi
      fonts:
        - asset: assets/fonts/Alibaba-PuHuiTi-Regular.otf
        - asset: assets/fonts/Alibaba-PuHuiTi-Light.otf
          weight: 400
        - asset: assets/fonts/Alibaba-PuHuiTi-Medium.otf
          weight: 600
        - asset: assets/fonts/Alibaba-PuHuiTi-Bold.otf
          weight: 700
        - asset: assets/fonts/Alibaba-PuHuiTi-Heavy.otf
          weight: 800
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
    - family: MaterialDesignIconFont
      fonts:
        - asset: packages/community_material_icon/fonts/materialdesignicons-webfont.ttf
